<?php

namespace App\Policies;

use App\User;
use App\Project;
use Illuminate\Auth\Access\AuthorizationException;
use Illuminate\Auth\Access\HandlesAuthorization;

class ProjectPolicy
{
    use HandlesAuthorization;
    
    /**
     * Determine whether the user can view the project.
     *
     *
     * note that before any of the logic is triggered here, 
     * any before hooks in the Laravel's Gate component will be triggered
     * see any before hooks added in the boot() in app/Providers/AuthServiceProvider
     * 
     * Note - policy class generated by artisan doesn't have any special propertiese or methods.
     * But every method added by developer is now mapped as an ability key for this object
     * 
     * 
     * 
     * 
     * 
     * @param  \App\User  $user
     * @param  \App\Project  $project
     * @return mixed
     */

    public function update(User $user, Project $project)
    {
        return $project->owner_id == $user->id;
    }

    public function create(User $user)
    {
        return $user->id > 0;
    }

    public function view(User $user, Project $project)
    {
        return $project->owner_id == $user->id;
    }

}
